apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    description: "Demo platform app (helm-guestbook)"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
  
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
